# SACA - Swahili Symptom Keyword Mapping
# Comprehensive mapping of Swahili medical terms to standardised symptom codes
# Based on WHO ETAT/IMCI clinical frameworks adapted for Mbinga District, Ruvuma Region, Tanzania

SYMPTOM_MAP = {

    # ─── FEVER ───────────────────────────────────────────────────────────────
    "homa": "fever",
    "homa kali": "high_fever",
    "homa ya juu": "high_fever",
    "homa ya chini": "low_fever",
    "homa ya muda mrefu": "prolonged_fever",
    "baridi na kutetemeka": "chills_rigors",
    "kutetemeka": "rigors",
    "jasho la usiku": "night_sweats",
    "mwili wa joto": "fever",
    "joto la mwili": "fever",

    # ─── NEUROLOGICAL ────────────────────────────────────────────────────────
    "degedege": "convulsions",
    "kifafa": "convulsions",
    "mshtuko": "convulsions",
    "mshtuko wa moyo": "convulsions",
    "kupoteza fahamu": "unconscious",
    "kupoteza ufahamu": "unconscious",
    "kuzimia": "unconscious",
    "kutokuwa macho": "altered_consciousness",
    "usingizi mzito": "altered_consciousness",
    "kulala sana": "altered_consciousness",
    "kutokujibu": "unresponsive",
    "kutokujibu sauti": "unresponsive",
    "shingo ngumu": "stiff_neck",
    "ugumu wa shingo": "stiff_neck",
    "maumivu ya shingo": "neck_pain",
    "maumivu ya kichwa": "headache",
    "kichwa kuuma": "headache",
    "maumivu makali ya kichwa": "severe_headache",
    "kizunguzungu": "dizziness",
    "kuchanganyikiwa": "confusion",
    "kutokuwa na akili": "confusion",
    "maono ya uongo": "hallucinations",
    "udhaifu wa upande mmoja": "focal_weakness",
    "kutoweza kutembea": "unable_to_walk",
    "kutoweza kusimama": "unable_to_stand",
    "kutoweza kukaa": "unable_to_sit",
    "unyonge": "prostration",
    "udhaifu mkubwa": "prostration",
    "kuchelewa kujibu": "altered_consciousness",
    "macho kuepuka mwanga": "photophobia",
    "kutopenda mwanga": "photophobia",
    "fontaneli kuvimba": "bulging_fontanelle",

    # ─── RESPIRATORY ─────────────────────────────────────────────────────────
    "kikohozi": "cough",
    "kukohoa": "cough",
    "kikohozi cha muda mrefu": "chronic_cough",
    "kukohoa damu": "haemoptysis",
    "damu kwenye makohozi": "haemoptysis",
    "upungufu wa pumzi": "difficulty_breathing",
    "kushindwa kupumua": "difficulty_breathing",
    "kupumua kwa shida": "respiratory_distress",
    "kupumua haraka": "fast_breathing",
    "pumzi fupi fupi": "fast_breathing",
    "kupumua polepole": "slow_breathing",
    "kukohoa na damu": "haemoptysis",
    "kifua kushuka ndani": "chest_indrawing",
    "kushuka kwa kifua": "chest_indrawing",
    "maumivu ya kifua": "chest_pain",
    "kifua kuuma": "chest_pain",
    "midomo ya buluu": "cyanosis",
    "ulimi wa buluu": "cyanosis",
    "ngozi ya buluu": "cyanosis",
    "kupumua kwa kelele": "stridor",
    "sauti ya kupumua": "stridor",
    "kupiga kelele kupumua": "stridor",
    "kupumua kwa nguvu": "respiratory_distress",
    "kutoweza kuzungumza kwa kupumua": "severe_respiratory_distress",
    "kutoweza kula kwa kupumua": "severe_respiratory_distress",
    "kutoa sauti ya kugongana": "grunting",
    "kupiga filimbi kupumua": "wheezing",
    "mzio wa njia ya hewa": "wheezing",

    # ─── GASTROINTESTINAL ────────────────────────────────────────────────────
    "kuhara": "diarrhoea",
    "tumbo kuendesha": "diarrhoea",
    "kuhara damu": "bloody_stool",
    "damu kwenye kinyesi": "bloody_stool",
    "kinyesi chekundu": "bloody_stool",
    "kuhara kwa muda mrefu": "persistent_diarrhoea",
    "kuhara zaidi ya wiki mbili": "persistent_diarrhoea",
    "kutapika": "vomiting",
    "kutapika kila kitu": "vomits_everything",
    "kutapika mara kwa mara": "persistent_vomiting",
    "kutapika damu": "haematemesis",
    "damu kwenye matapishi": "haematemesis",
    "kichefuchefu": "nausea",
    "tumbo kuuma": "abdominal_pain",
    "maumivu ya tumbo": "abdominal_pain",
    "maumivu makali ya tumbo": "severe_abdominal_pain",
    "tumbo gumu": "abdominal_rigidity",
    "tumbo kujaa": "abdominal_distension",
    "tumbo kuvimba": "abdominal_distension",
    "kushindwa kunywa": "unable_to_drink",
    "kutoweza kunywa": "unable_to_drink",
    "kushindwa kunyonyesha": "unable_to_breastfeed",
    "kutoweza kunyonya": "unable_to_breastfeed",
    "ini kuvimba": "hepatomegaly",
    "wengu kuvimba": "splenomegaly",
    "ini na wengu kuvimba": "hepatosplenomegaly",
    "macho ya njano": "jaundice",
    "ngozi ya njano": "jaundice",
    "manjano macho": "jaundice",
    "mkojo mweusi": "dark_urine",
    "mkojo wa kahawia": "dark_urine",
    "kuvimbiwa": "constipation",
    "kutokupata haja kubwa": "constipation",

    # ─── DEHYDRATION ─────────────────────────────────────────────────────────
    "macho yaliyozama": "sunken_eyes",
    "macho ya ndani": "sunken_eyes",
    "kiu kikubwa": "extreme_thirst",
    "kiu sana": "extreme_thirst",
    "ngozi isiyo na unyevu": "skin_turgor_reduced",
    "ngozi kuumia ukishika": "skin_turgor_reduced",
    "mdomo mkavu": "dry_mouth",
    "midomo ya ukame": "dry_mouth",
    "mkojo kidogo": "reduced_urine",
    "kukojoa kidogo": "reduced_urine",
    "kutokojoa": "no_urine_output",
    "wasiwasi na kukera": "restless_irritable",
    "kukera sana": "restless_irritable",

    # ─── CARDIOVASCULAR / SHOCK ──────────────────────────────────────────────
    "miguu baridi": "cold_extremities",
    "mikono baridi": "cold_extremities",
    "mapigo ya moyo haraka": "tachycardia",
    "moyo kupiga haraka": "tachycardia",
    "mapigo dhaifu": "weak_pulse",
    "pigo dhaifu": "weak_pulse",
    "kutokudumisha damu": "uncontrolled_bleeding",
    "kutoka damu nyingi": "uncontrolled_bleeding",
    "damu nyingi": "uncontrolled_bleeding",
    "shinikizo la damu chini": "low_blood_pressure",
    "shinikizo la damu juu": "high_blood_pressure",
    "vidole vya buluu": "cyanosis",

    # ─── DERMATOLOGICAL ──────────────────────────────────────────────────────
    "weupe wa viganja": "severe_pallor",
    "viganja vya rangi nyeupe": "severe_pallor",
    "rangi ya ngozi kupotea": "severe_pallor",
    "upele mdogo mdogo": "petechial_rash",
    "upele wa damu": "purpuric_rash",
    "vidonda vya ngozi": "skin_lesions",
    "uvimbe wa miguu miwili": "bilateral_oedema",
    "miguu kuvimba": "bilateral_oedema",
    "mikono kuvimba": "oedema",
    "uso kuvimba": "oedema",
    "kuuma mahali palipoumwa na nyoka": "bite_site_pain",
    "uvimbe mahali palipoumwa": "bite_site_swelling",
    "vidonda vya kuoza": "necrosis",
    "ngozi kufa": "necrosis",
    "mabubujiko": "blistering",

    # ─── MUSCULOSKELETAL ─────────────────────────────────────────────────────
    "maumivu ya viungo": "joint_pain",
    "viungo kuuma": "joint_pain",
    "maumivu ya misuli": "myalgia",
    "misuli kuuma": "myalgia",
    "maumivu ya mgongo": "back_pain",
    "mgongo kuuma": "back_pain",
    "mfupa kuvunjika": "fracture",
    "mfupa uliovunjika": "fracture",
    "mfupa wazi": "compound_fracture",
    "kutoweza kutumia mkono": "limb_dysfunction",
    "kutoweza kutumia mguu": "limb_dysfunction",

    # ─── MALNUTRITION ────────────────────────────────────────────────────────
    "kupoteza uzito": "weight_loss",
    "uzito kupungua": "weight_loss",
    "kukua polepole": "failure_to_thrive",
    "kutokukua vizuri": "failure_to_thrive",
    "kukonda sana": "severe_wasting",
    "mwili kukonda": "severe_wasting",
    "kutokula": "anorexia",
    "kutaka kula": "appetite_loss",
    "hamu ya kula kupotea": "appetite_loss",
    "nywele za rangi ya njano": "kwashiorkor_signs",
    "nywele nyekundu": "kwashiorkor_signs",

    # ─── TUBERCULOSIS SPECIFIC ───────────────────────────────────────────────
    "kukohoa zaidi ya wiki mbili": "chronic_cough",
    "jasho usiku": "night_sweats",
    "uzito kupotea": "weight_loss",
    "homa ya muda mrefu na kikohozi": "tb_symptoms",
    "kuwasiliana na mtu mwenye kifua kikuu": "tb_contact",
    "mawasiliano na mgonjwa wa tb": "tb_contact",

    # ─── MALARIA SPECIFIC ────────────────────────────────────────────────────
    "malaria": "malaria_confirmed",
    "vipimo vya malaria chanya": "malaria_confirmed",
    "homa ya malaria": "malaria_confirmed",
    "baridi ya malaria": "malaria_confirmed",
    "ugonjwa wa malaria": "malaria_confirmed",

    # ─── OBSTETRIC ───────────────────────────────────────────────────────────
    "mimba": "pregnancy",
    "mjamzito": "pregnancy",
    "kutoka damu ukiwa mjamzito": "antepartum_bleeding",
    "damu wakati wa mimba": "antepartum_bleeding",
    "kutoka damu baada ya kujifungua": "postpartum_haemorrhage",
    "damu nyingi baada ya kujifungua": "postpartum_haemorrhage",
    "degedege ukiwa mjamzito": "eclampsia",
    "mshtuko wakati wa mimba": "eclampsia",
    "kichwa kuuma na macho ya ukungu ukiwa mjamzito": "pre_eclampsia",
    "shinikizo la damu juu ukiwa mjamzito": "pre_eclampsia",
    "kuzaa kwa muda mrefu": "prolonged_labour",
    "uchungu wa kuzaa zaidi ya masaa kumi na mbili": "prolonged_labour",
    "placenta kutoka baadaye": "retained_placenta",
    "kondo la nyuma kutoka baadaye": "retained_placenta",
    "homa baada ya kujifungua": "puerperal_sepsis",
    "harufu mbaya ya uke baada ya kujifungua": "puerperal_sepsis",
    "maumivu ya tumbo baada ya kujifungua": "puerperal_sepsis",
    "damu kidogo ukiwa mjamzito": "antepartum_bleeding",

    # ─── URINARY ─────────────────────────────────────────────────────────────
    "maumivu ya mkojo": "dysuria",
    "kukojoa kwa uchungu": "dysuria",
    "kukojoa mara kwa mara": "urinary_frequency",
    "damu kwenye mkojo": "haematuria",
    "mkojo wenye damu": "haematuria",

    # ─── TRAUMA / INJURY ─────────────────────────────────────────────────────
    "kuumia": "trauma",
    "ajali": "trauma",
    "kuanguka": "fall",
    "kupigwa": "assault",
    "jeraha": "wound",
    "jeraha kubwa": "significant_wound",
    "jeraha dogo": "minor_wound",
    "kuungua": "burns",
    "moto kuungua": "burns",
    "mdomo wa moto": "burns",
    "jeraha la kichwa": "head_injury",
    "kichwa kuumia": "head_injury",
    "michubuko": "bruising",
    "kuvimba baada ya kuumia": "swelling_post_trauma",
    "damu isiyosimama": "uncontrolled_bleeding",

    # ─── SNAKE BITE ──────────────────────────────────────────────────────────
    "kuumwa na nyoka": "snake_bite",
    "nyoka kuuma": "snake_bite",
    "sumu ya nyoka": "snake_envenomation",
    "uvimbe baada ya kuumwa na nyoka": "bite_site_swelling",
    "maumivu ya kuumwa na nyoka": "bite_site_pain",
    "kushindwa kupumua baada ya kuumwa na nyoka": "neurotoxic_envenomation",
    "kope kushuka baada ya kuumwa na nyoka": "ptosis",
    "damu isiyokauka baada ya kuumwa na nyoka": "coagulopathy",
    "uvimbe mkubwa": "bite_site_swelling",
    "uvimbe wa haraka": "bite_site_swelling",

    # ─── GENERAL DANGER SIGNS (IMCI) ─────────────────────────────────────────
    "hawezi kunywa": "unable_to_drink",
    "anatapika kila kitu": "vomits_everything",
    "amepoteza fahamu": "unconscious",
    "ana degedege": "convulsions",
    "hana nguvu kabisa": "prostration",
    "pumzi ya haraka sana": "fast_breathing",
    "kifua kushuka": "chest_indrawing",
    "shingo ngumu na homa": "stiff_neck_with_fever",

}

SYMPTOM_DESCRIPTIONS = {
    "fever": "Fever",
    "high_fever": "High fever",
    "low_fever": "Low-grade fever",
    "prolonged_fever": "Prolonged fever (more than 7 days)",
    "chills_rigors": "Chills and rigors",
    "rigors": "Rigors (shaking chills)",
    "night_sweats": "Night sweats",
    "convulsions": "Convulsions / seizures (IMCI danger sign)",
    "unconscious": "Loss of consciousness (IMCI danger sign)",
    "altered_consciousness": "Altered consciousness / drowsiness",
    "unresponsive": "Unresponsive to voice or touch",
    "stiff_neck": "Stiff neck (meningitis sign)",
    "neck_pain": "Neck pain",
    "headache": "Headache",
    "severe_headache": "Severe headache",
    "dizziness": "Dizziness",
    "confusion": "Confusion / disorientation",
    "hallucinations": "Hallucinations",
    "focal_weakness": "Weakness on one side of body",
    "unable_to_walk": "Unable to walk",
    "unable_to_stand": "Unable to stand",
    "unable_to_sit": "Unable to sit up",
    "prostration": "Prostration / severe weakness (danger sign)",
    "photophobia": "Sensitivity to light (meningitis sign)",
    "bulging_fontanelle": "Bulging fontanelle in infant (meningitis sign)",
    "cough": "Cough",
    "chronic_cough": "Chronic cough more than 2 weeks (TB sign)",
    "haemoptysis": "Coughing blood (haemoptysis)",
    "difficulty_breathing": "Difficulty breathing",
    "respiratory_distress": "Respiratory distress",
    "severe_respiratory_distress": "Severe respiratory distress (danger sign)",
    "fast_breathing": "Fast breathing / tachypnoea (pneumonia sign)",
    "slow_breathing": "Slow breathing",
    "chest_indrawing": "Chest indrawing (severe pneumonia sign)",
    "chest_pain": "Chest pain",
    "cyanosis": "Cyanosis - blue lips or tongue (danger sign)",
    "stridor": "Stridor - noisy breathing (danger sign)",
    "grunting": "Grunting sound when breathing",
    "wheezing": "Wheezing",
    "diarrhoea": "Diarrhoea",
    "bloody_stool": "Blood in stool - dysentery",
    "persistent_diarrhoea": "Persistent diarrhoea more than 14 days",
    "vomiting": "Vomiting",
    "vomits_everything": "Vomiting everything (IMCI danger sign)",
    "persistent_vomiting": "Persistent / repeated vomiting",
    "haematemesis": "Vomiting blood",
    "nausea": "Nausea",
    "abdominal_pain": "Abdominal pain",
    "severe_abdominal_pain": "Severe abdominal pain",
    "abdominal_rigidity": "Rigid abdomen (peritonitis sign)",
    "abdominal_distension": "Abdominal distension / bloating",
    "unable_to_drink": "Unable to drink (IMCI danger sign)",
    "unable_to_breastfeed": "Unable to breastfeed (IMCI danger sign)",
    "hepatomegaly": "Enlarged liver",
    "splenomegaly": "Enlarged spleen",
    "hepatosplenomegaly": "Enlarged liver and spleen (malaria sign)",
    "jaundice": "Jaundice - yellow eyes or skin",
    "dark_urine": "Dark urine (jaundice / malaria sign)",
    "constipation": "Constipation",
    "sunken_eyes": "Sunken eyes (dehydration sign)",
    "extreme_thirst": "Extreme thirst (dehydration sign)",
    "skin_turgor_reduced": "Slow skin pinch - dehydration sign",
    "dry_mouth": "Dry mouth (dehydration sign)",
    "reduced_urine": "Reduced urine output",
    "no_urine_output": "No urine output",
    "restless_irritable": "Restless or irritable (dehydration sign)",
    "cold_extremities": "Cold hands or feet (shock sign - CRITICAL)",
    "tachycardia": "Rapid heartbeat (tachycardia)",
    "weak_pulse": "Weak pulse (shock sign)",
    "uncontrolled_bleeding": "Uncontrolled / heavy bleeding (danger sign)",
    "low_blood_pressure": "Low blood pressure",
    "high_blood_pressure": "High blood pressure (hypertension)",
    "severe_pallor": "Severe pallor - white palms (severe anaemia sign)",
    "petechial_rash": "Petechial rash - small red spots",
    "purpuric_rash": "Purpuric rash (meningococcaemia sign - CRITICAL)",
    "skin_lesions": "Skin lesions / sores",
    "bilateral_oedema": "Bilateral leg oedema (kwashiorkor / heart failure sign)",
    "oedema": "Swelling / oedema",
    "bite_site_pain": "Pain at bite site (snake bite)",
    "bite_site_swelling": "Swelling at bite site (snake bite)",
    "necrosis": "Tissue death / necrosis at bite site",
    "blistering": "Blistering at wound site",
    "joint_pain": "Joint pain (malaria / typhoid sign)",
    "myalgia": "Muscle pain (myalgia)",
    "back_pain": "Back pain",
    "fracture": "Fracture / broken bone",
    "compound_fracture": "Compound fracture (bone piercing skin)",
    "limb_dysfunction": "Unable to use limb",
    "weight_loss": "Weight loss (TB / malnutrition / HIV sign)",
    "failure_to_thrive": "Failure to thrive in child",
    "severe_wasting": "Severe wasting / extreme thinness (SAM)",
    "anorexia": "Loss of appetite / anorexia",
    "appetite_loss": "Loss of appetite",
    "kwashiorkor_signs": "Kwashiorkor signs (yellow or reddish hair)",
    "tb_symptoms": "TB symptom cluster (fever + cough)",
    "tb_contact": "Contact with TB patient",
    "malaria_confirmed": "Confirmed malaria (positive test)",
    "pregnancy": "Pregnancy",
    "antepartum_bleeding": "Vaginal bleeding during pregnancy",
    "postpartum_haemorrhage": "Heavy bleeding after delivery (PPH - CRITICAL)",
    "eclampsia": "Convulsions in pregnancy (eclampsia - CRITICAL)",
    "pre_eclampsia": "Pre-eclampsia (severe headache + high BP in pregnancy)",
    "prolonged_labour": "Prolonged labour more than 12 hours",
    "retained_placenta": "Retained placenta after delivery",
    "puerperal_sepsis": "Puerperal sepsis (fever + foul discharge after delivery)",
    "dysuria": "Painful urination (UTI sign)",
    "urinary_frequency": "Frequent urination",
    "haematuria": "Blood in urine (haematuria)",
    "trauma": "Trauma / injury",
    "fall": "Fall / fall from height",
    "assault": "Assault / physical attack",
    "wound": "Wound / laceration",
    "significant_wound": "Significant wound",
    "minor_wound": "Minor wound",
    "burns": "Burns",
    "head_injury": "Head injury",
    "bruising": "Bruising / contusion",
    "swelling_post_trauma": "Swelling after trauma",
    "snake_bite": "Snake bite",
    "snake_envenomation": "Snake envenomation",
    "neurotoxic_envenomation": "Neurotoxic snake envenomation (respiratory paralysis)",
    "ptosis": "Drooping eyelids (neurotoxic snake sign)",
    "coagulopathy": "Bleeding disorder after snake bite",
    "stiff_neck_with_fever": "Stiff neck with fever (meningitis - CRITICAL)",
}

# Severity override keywords - these always trigger CRITICAL regardless of other symptoms
CRITICAL_OVERRIDE_KEYWORDS = [
    "unconscious", "convulsions", "unable_to_drink", "unable_to_breastfeed",
    "vomits_everything", "severe_respiratory_distress", "cyanosis",
    "uncontrolled_bleeding", "stridor", "eclampsia", "purpuric_rash",
    "cold_extremities"
]

def extract_symptoms(text: str) -> list[str]:
    """
    Extract standardised symptom codes from raw Swahili text input.
    Returns list of symptom codes found in the text.
    """
    text = text.lower().strip()
    found_symptoms = []

    # Check multi-word phrases first (longer phrases take priority)
    sorted_keywords = sorted(SYMPTOM_MAP.keys(), key=len, reverse=True)

    for keyword in sorted_keywords:
        if keyword in text:
            symptom_code = SYMPTOM_MAP[keyword]
            if symptom_code not in found_symptoms:
                found_symptoms.append(symptom_code)

    return found_symptoms


if __name__ == "__main__":
    # Quick test
    test_inputs = [
        "mgonjwa ana homa na degedege",
        "ana kikohozi na kupumua haraka",
        "ana kuhara na macho yaliyozama",
        "maumivu ya kichwa na shingo ngumu",
        "kuumwa na nyoka na uvimbe mkubwa",
        "mjamzito ana damu nyingi",
    ]

    for text in test_inputs:
        symptoms = extract_symptoms(text)
        print(f"Input: {text}")
        print(f"Symptoms: {symptoms}")
        print()